### ISSUE TITLE
Add game sounds

### ISSUE THREAD

**Issue by kalaithuli** [acmpesuecc/Snail_Hurdle_Hop#1]
Add sounds to the game - one while player runs and one while player jumps !

**Comment by pratham-exe** [comment]
assign me this pls

**Comment by PandaTGOS** [comment]
can I get assigned to this ?

**Comment by Lalith2907** [comment]
can i get assigned to this?

**Comment by Rojas-Binny** [comment]
PLs assign

**Comment by SafwanAhmed08** [comment]
assign please

**Comment by Archit-Rode** [comment]
Assign me please

**Comment by kalaithuli** [comment]
> PLs assign

@Rojas-Binny you have been assigned

**Comment by shakirth-anisha** [comment]
Can I get assigned to this??

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by PsychCodez** [comment]
assign me please

**Comment by kalaithuli** [comment]
> assign me this pls

@pratham-exe you have been assigned

**Comment by neethanm** [comment]
can i be assigned to this #1?

**Comment by Alley2717** [comment]
can i be assigned

**Comment by kalaithuli** [comment]
> can i be assigned to this #1?

@neethanm you have been assigned

**Comment by aniruddhajoshi100** [comment]
can i get this assigned?

**Comment by AmeyaKhanzode** [comment]
can i get assigned to this rn? please
