### ISSUE TITLE
Add more hurdles

### ISSUE THREAD

**Issue by kalaithuli** [acmpesuecc/Snail_Hurdle_Hop#2]
Add more hurdles for our man to cross!! 
Add a variety of obstacles - for example, cacti or worms , etc.

**Comment by PandaTGOS** [comment]
can I get assigned to this ?

**Comment by Sanjaya2204** [comment]
assign bro plss

**Comment by rahuljjacob** [comment]
can i get assigned to one of the issues, if not please add me to the queue

**Comment by kalaithuli** [comment]
> can I get assigned to this ?

@PandaTGOS you have been assigned

**Comment by ProSai8055** [comment]
i will add more tough hurdles assign me next

**Comment by PandaTGOS** [comment]
Still working on it

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by neethanm** [comment]
can i get assigned to this #2?
