### ISSUE TITLE
Add high score

### ISSUE THREAD

**Issue by kalaithuli** [acmpesuecc/Snail_Hurdle_Hop#3]
Calculate the score as the game progresses and keep a track of the player's high score. When the player gets out, a page should be displayed with the current score, high score, and  play button.

**Comment by Manvith-M-Nayak** [comment]
can i get assigned ??

**Comment by Sanjaya2204** [comment]
assign broo plss

**Comment by rahuljjacob** [comment]
can i get this assigned please

**Comment by siribins** [comment]
can i get assigned

**Comment by Keeru-2005** [comment]
can i get assigned?
i will start working on this
hope u understand

**Comment by HackerGlory** [comment]
PLEASE ASSIGN ME TO THIS. thank you

**Comment by SafwanAhmed08** [comment]
please assign me this i already completed

**Comment by kalaithuli** [comment]
> can i get assigned ??

@Manvith-M-Nayak you have been assigned

**Comment by kavs2803** [comment]
can i be assigned please?
